---
title: "Plotly Examples"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

My name is Gloria I  male websites _with intercative plots_ 
## Let's make some plots

```{r, message=FALSE}
library(tidyverse) 
library(viridis) 
library(p8105.datasets)

library(plotly)
```



```{r}
set.seed(1)

data(nyc_airbnb)
nyc_airbnb =
   nyc_airbnb %>%
   mutate(rating = review_scores_location / 2) %>%
   select(
     neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
   filter(
!is.na(rating), neighbourhood_group == "Manhattan", room_type == "Entire home/apt", price %in% 100:500) %>%
   sample_n(5000)

```
## scatter plot
```{r}
nyc_airbnb %>%
  plot_ly(x = ~lat, y = ~long, type = "scatter", mode = "markers",
          color = ~price, alpha = 0.5)

nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>%
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)

```

## boxplot
```{r}
nyc_airbnb %>%
   mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>%
   plot_ly(y = ~price, color = ~neighbourhood, type = "box",
           colors = "Set2")
```

## histogram/ barplot
```{r}
nyc_airbnb %>%
   count(neighbourhood) %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>%
   plot_ly(x = ~neighbourhood, y = ~n, type = "bar")
```

## Covert ggplot to interctive plots
```{r}
scatter_ggplot =
   nyc_airbnb %>%
   ggplot(aes(x = lat, y = long, color = price)) +
   geom_point(alpha = 0.25) +
   scale_color_viridis() +
   coord_cartesian() +
   theme_classic()
ggplotly(scatter_ggplot)
```


















